// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Speakers.proto

package org.DS.robertproject.SmartBuildingGRPC;

public interface boolResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartBuildingGRPC.boolResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool msg = 2;</code>
   */
  boolean getMsg();
}
