// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Speakers.proto

package org.DS.robertproject.SmartBuildingGRPC;

public interface boolRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartBuildingGRPC.boolRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool msg = 2;</code>
   */
  boolean getMsg();
}
