// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Heating.proto

package org.DS.robertproject.SmartBuildingGRPC;

public interface booleanRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartBuildingGRPC.booleanRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool msg = 2;</code>
   */
  boolean getMsg();
}
