// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Heating.proto

package org.DS.robertproject.SmartBuildingGRPC;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartBuildingGRPC.Empty)
    com.google.protobuf.MessageOrBuilder {
}
