// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Heating.proto

package org.DS.robertproject.SmartBuildingGRPC;

public interface heatingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartBuildingGRPC.heatingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string aname = 4;</code>
   */
  java.lang.String getAname();
  /**
   * <code>string aname = 4;</code>
   */
  com.google.protobuf.ByteString
      getAnameBytes();

  /**
   * <code>string status = 5;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 5;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 temperature = 6;</code>
   */
  int getTemperature();

  /**
   * <code>int32 speed = 7;</code>
   */
  int getSpeed();
}
