// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Light.proto

package org.DS.robertproject.SmartBuildingGRPC;

public interface lampRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartBuildingGRPC.lampResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string aname = 4;</code>
   */
  java.lang.String getAname();
  /**
   * <code>string aname = 4;</code>
   */
  com.google.protobuf.ByteString
      getAnameBytes();

  /**
   * <code>string status = 5;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 5;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 brightness = 6;</code>
   */
  int getBrightness();
}
