// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Heating.proto

package org.DS.robertproject.SmartBuildingGRPC;

public interface valueRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartBuildingGRPC.valueRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 length = 3;</code>
   */
  int getLength();
}
